import React from 'react'
import { Navbar } from '@elements'
import Head from 'next/head'

export const IndexModule: React.FC = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-backgroundColor w-full min-h-screen flex justify-center">
        <div className=" min-h-screen max-w-[1440px] w-full items-center flex flex-col">
          <Navbar />
          <div className="w-1/2 h-full ">
            <div className="gap-4 flex flex-col">
              <p className="font-poppinsBold text-white text-4xl">
                Welcome back,
              </p>
              <p className="font-poppinsBold text-blueOnBackgroud text-4xl">
                @username
              </p>
            </div>
            <div className="mt-10">
              <textarea
                className="h-[189.82px] w-full resize-none rounded-md p-3 bg-backgroundColor border-2 border-blueOnBackgroud shadow-sm shadow-blueOnBackgroud text-white focus:outline-0 focus:shadow-lg focus:shadow-blueOnBackgroud transition-shadow"
                placeholder="What’s happening?"
              />
            </div>
          </div>
        </div>
      </main>
    </>
  )
}
