import { Navbar } from '@elements'
import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-backgroundColor w-full min-h-screen flex justify-center">
        <div className="border border-red-500 min-h-screen max-w-[1440px] w-full">
          <Navbar />
          <div className="h-screen"></div>
        </div>
      </main>
    </>
  )
}
